version: 2.1
jobs:

  #------------------------------------------------------------
  # 1. 安装依赖
  #------------------------------------------------------------
  install-dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps

      - run:
          name: 'Install dependencies'
          command: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  #------------------------------------------------------------
  # 2. 构建
  #------------------------------------------------------------
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - attach_workspace:
          at: ~/project
      
      - run:
          name: 'Run build'
          command: yarn build
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - .vuepress/dist
  
  #------------------------------------------------------------
  # 2.5 增量部署
  #------------------------------------------------------------
  deploy-rsync:
    docker:
      - image: instrumentisto/rsync-ssh:latest
    steps:
      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "65:b3:e1:50:05:82:37:0a:a5:ae:33:ea:0e:ad:63:c3"
      
      - run:
          name: Deploy Over Rsync
          command: |
            ls -hl .vuepress/dist
            rsync -az --progress --delete-after -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" .vuepress/dist/ $SSH_DEPLOY_USER@$SSH_HOST:/data/temp/rsync

  #------------------------------------------------------------
  # 3. 部署
  #------------------------------------------------------------
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "65:b3:e1:50:05:82:37:0a:a5:ae:33:ea:0e:ad:63:c3"
    
      - run:
          name: Deploy Over SSH
          command: |
            tar -czvf .vuepress/blog.tar.gz --directory=.vuepress dist
            scp -p .vuepress/blog.tar.gz $SSH_DEPLOY_USER@$SSH_HOST:/data/temp
            ssh $SSH_DEPLOY_USER@$SSH_HOST "rm -rf /data/blog/*; tar -xvf /data/temp/blog.tar.gz --strip-components=1 -C /data/blog/"

workflows:
  build:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy-rsync:
          requires:
            - build
          context: deploy
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
          context: deploy